### ISSUE TITLE
Add ability to sort changelog entries alphabetically

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/unclog#146]
At present, individual changelog entries are sorted by way of their issue/PR number, but this can result in somewhat chaotic-looking changelogs if entries are prefixed by, for example, a module name ([example](https://github.com/cometbft/cometbft/blob/ded55d7bd32a58a0cbce8bfe89a56d15ef2079cb/CHANGELOG.md#v100-alpha1)).

A new configuration file parameter should be provided to allow for configuration of this value:

```toml
# The default behaviour
sort_entries_by = "id"

# Sort entries alphabetically by way of the entry text
sort_entries_by = "entry-text"
```
