### ISSUE TITLE
Component's name is not used when rendering the changelog

### ISSUE THREAD

**Issue by romac** [informalsystems/unclog#19]
1. Use the following configuration 

```toml
project_url = "https://github.com/informalsystems/ibc-rs"

[components]
general_entries_title = "General"
entry_indent = 2

    [components.all]
    ibc             = { name = "IBC Modules",     path = "modules" }
    ibc-relayer     = { name = "Relayer Library", path = "relayer" }
    ibc-relayer-cli = { name = "Relayer CLI",     path = "relayer-cli" }
    guide           = { name = "Guide",           path = "guide" }
```

<details>
<summary><strong>Click to show full config</strong></summary>

```toml
# The GitHub URL for your project.
#
# This is mainly necessary if you need to automatically generate changelog
# entries directly from the CLI. Right now we only support GitHub, but if
# anyone wants GitLab support please let us know and we'll try implement it
# too.
project_url = "https://github.com/informalsystems/ibc-rs"

# The file to use as a Handlebars template for changes added directly through
# the CLI.
#
# Assumes that relative paths are relative to the `.changelog` folder. If this
# file does not exist, a default template will be used.
change_template = "change-template.md"

# The number of characters at which to wrap entries automatically added from
# the CLI.
wrap = 80

# The heading right at the beginning of the changelog.
heading = "# CHANGELOG"

# What style of bullet to use for the instances where unclog has to generate
# bullets for you. Can be "-" or "*".
bullet_style = "-"

# The message to output when your changelog has no entries yet.
empty_msg = "Nothing to see here! Add some entries to get started."

# The name of the file (relative to the `.changelog` directory) to use as an
# epilogue for your changelog (will be appended as-is to the end of your
# generated changelog).
epilogue_filename = "epilogue.md"


# Settings relating to unreleased changelog entries.
[unreleased]

# The name of the folder containing unreleased entries, relative to the
# `.changelog` folder.
folder = "unreleased"

# The heading to use for the unreleased entries section.
heading = "## Unreleased"


# Settings relating to sets (groups) of changes in the changelog. For example,
# the "BREAKING CHANGES" section would be considered a change set.
[change_sets]

# The filename containing a summary of the intended changes. Relative to the
# change set folder (e.g. `.changelog/unreleased/breaking-changes/summary.md`).
summary_filename = "summary.md"

# The extension of files in a change set.
entry_ext = "md"


# Settings related to components/sub-modules. Only relevant if you make use of
# components/sub-modules.
[components]

# The title to use for the section of entries not relating to a specific
# component.
general_entries_title = "General"

# The number of spaces to inject before each component-related entry.
entry_indent = 2

    # The components themselves. Each component has a name (used when rendered
    # to Markdown) and a path relative to the project folder (i.e. relative to
    # the parent of the `.changelog` folder).
    [components.all]
    ibc             = { name = "IBC Modules",     path = "modules" }
    ibc-relayer     = { name = "Relayer Library", path = "relayer" }
    ibc-relayer-cli = { name = "Relayer CLI",     path = "relayer-cli" }
    guide           = { name = "Guide",           path = "guide" }
```

</details>

2. Add a new entry for the `ibc-relayer` component (or any other of the components listed above)

```
❯ unclog add -i some-new-feature \
>   -n 23 \
>   -c ibc-relayer \
>   -s breaking-changes \
>   -m "Some *new* feature"
15:47:31 [INFO] Attempting to load configuration file from: .changelog/config.toml
15:47:31 [INFO] Loading change template from: .changelog/change-template.md
15:47:31 [INFO] Created directory: .changelog/unreleased/breaking-changes
15:47:31 [INFO] Created directory: .changelog/unreleased/breaking-changes/ibc-relayer
15:47:31 [INFO] Wrote entry to: .changelog/unreleased/breaking-changes/ibc-relayer/23-some-new-feature.md
```

3. Build the changelog

```markdown
❯ unclog build --unreleased
15:47:58 [INFO] Attempting to load configuration file from: .changelog/config.toml
15:47:58 [INFO] Attempting to load changelog from directory: .changelog
15:47:58 [INFO] Success!
## Unreleased

### BREAKING CHANGES

- [ibc-relayer](relayer)
  - Some *new* feature ([#23](https://github.com/informalsystems/ibc-
    rs/issues/23))
```

4. Notice that the top-level item for the `ibc-relayer` components does not use the name provided in the configuration (*ibc-relayer* instead of _Relayer Library_)
